### ISSUE TITLE
Please add a readme about this repo.

### ISSUE THREAD

**Issue by SarveshMD** [codebling/arch-rtl8188fu-kelebek333-dkms-git#1]
By looking at the title, I think this is a wireless network adapter driver repository for arch Linux. But, I don't see any installation guides for it. Adding a readme will make it usable for users.

**Comment by codebling** [comment]
It is indeed an Arch Linux package repo. I was not expecting Arch users to find the package through Github, but through the AUR, [where it is listed](https://aur.archlinux.org/packages/8188fu-kelebek333-dkms-git/). This package can be installed the same way [any other AUR package is](https://wiki.archlinux.org/title/Arch_User_Repository), [using `makepkg`](https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages) or [with an AUR helper](https://wiki.archlinux.org/title/AUR_helpers). 

How did you find this package? Are you an Arch user? Have you installed packages from AUR before?

Most packages repos do not include any files which are not strictly needed for installation (not even `.gitignore`), to the point where it seems to be considered poor form to have any. That being said, it couldn't hurt much. I'm curious about your answers to the questions above. Thanks for the comment, it's always nice to get feedback.

**Comment by SarveshMD** [comment]
> It is indeed an Arch Linux package repo. I was not expecting Arch users to find the package through Github, but through the AUR, [where it is listed](https://aur.archlinux.org/packages/8188fu-kelebek333-dkms-git/). This package can be installed the same way [any other AUR package is](https://wiki.archlinux.org/title/Arch_User_Repository), [using `makepkg`](https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages) or [with an AUR helper](https://wiki.archlinux.org/title/AUR_helpers).
> 
> How did you find this package? Are you an Arch user? Have you installed packages from AUR before?
> 
> Most packages repos do not include any files which are not strictly needed for installation (not even `.gitignore`), to the point where it seems to be considered poor form to have any. That being said, it couldn't hurt much. I'm curious about your answers to the questions above. Thanks for the comment, it's always nice to get feedback.

Thanks for replying !
I just searched for rtl8188fu on github, and I got around twelve results. This repository was one of those twelve results.
I am not an arch user, I use Linux Mint, but I just wanted to try out different distros so when I landed on garuda linux, I wanted to install an Arch Driver for rtl8188fu Realtek Wi-Fi adapter. So when I saw the word "arch" in the title, I wanted to install this. Since I was new to arch when trying out Garuda, I wasn't able to install that. So, I opened this issue. I haven't installed any AUR packages before.

**Comment by codebling** [comment]
Ok, I understand! It's likely that even if I do include a README, it won't have the information you're looking for. Let me quickly check to see what Garuda looks like, maybe I can create some instructions for you.

**Comment by codebling** [comment]
Garuda seems to use the same package management as Arch. It looks pretty cool. 

The [Arch Wiki](https://wiki.archlinux.org/) is a veritable treasure trove of information. I suggest you read the articles on [`pacman`](https://wiki.archlinux.org/title/Pacman), [`makepkg`](https://wiki.archlinux.org/title/Makepkg), and [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) if you want to get into the nitty-gritty of understanding how the package system works. 

If you do not want to dive headfirst into the details of package management, you *should* be able to build and install the package by simply cloning this repo and running `makepkg -sri` in it. If that doesn't work, then I won't be able to help you and you'd be better off posting in the Garuda Linux forums. 

That being said, this repo is essentially only a recipe for building and installing the actual driver, which you can find at https://github.com/kelebek333/rtl8188fu
While you *could* also follow the instructions there to install it, you wouldn't be adhering to the package management principles of Arch-derived linuxes, but that might be ok by you. 

Good luck!

**Comment by SarveshMD** [comment]
> Garuda seems to use the same package management as Arch. It looks pretty cool.
> 
> The [Arch Wiki](https://wiki.archlinux.org/) is a veritable treasure trove of information. I suggest you read the articles on [`pacman`](https://wiki.archlinux.org/title/Pacman), [`makepkg`](https://wiki.archlinux.org/title/Makepkg), and [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) if you want to get into the nitty-gritty of understanding how the package system works.
> 
> If you do not want to dive headfirst into the details of package management, you _should_ be able to build and install the package by simply cloning this repo and running `makepkg -sri` in it. If that doesn't work, then I won't be able to help you and you'd be better off posting in the Garuda Linux forums.
> 
> That being said, this repo is essentially only a recipe for building and installing the actual driver, which you can find at https://github.com/kelebek333/rtl8188fu
> While you _could_ also follow the instructions there to install it, you wouldn't be adhering to the package management principles of Arch-derived linuxes, but that might be ok by you.
> 
> Good luck!

Thanks a lot @codebling.
